# Funding platforms for AI Prompts Library
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: unisone
# patreon: # Uncomment and add username when available
# ko_fi: # Uncomment and add username when available
# buy_me_a_coffee: # Uncomment and add username when available
# custom: ['https://your-custom-link.com']
