name: "💡 Feature Request"
description: Suggest an improvement or new category
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to improve the library? We'd love to hear it!

  - type: dropdown
    id: request-type
    attributes:
      label: Request Type
      options:
        - New category
        - Template improvement
        - Documentation enhancement
        - Tooling / automation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your idea in detail
      placeholder: "It would be great if..."
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would this help you or others?
      placeholder: "This would help when..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternatives?
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to help implement this feature
